version: '3.5'

services:
  db:
    image: mysql:latest
    # command: --default-authentication-plugin=mysql_native_password
    container_name: gruberino-db
    environment:
      MYSQL_DATABASE: gruberinodb
      MYSQL_USER: gruberino
      MYSQL_PASSWORD: masterkey63763145
      MYSQL_ROOT_PASSWORD: XpWUu$xcs3XCS8Z2Yna3zeerD5gYvH%?
    volumes:
      - /opt/mysql/data:/var/lib/mysql
    networks:
      - gruberino-internal
    restart: always

  phpmyadmin:
    image: phpmyadmin
    container_name: gruberino-phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - gruberino-internal
    restart: always

networks:
  gruberino-internal:
    name: gruberino-internal
    driver: bridge